name: Create Release Branch and PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH_NAME: release/${{ github.event.inputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Create and push release branch
        run: |
          git checkout -b ${{ env.RELEASE_BRANCH_NAME }}
          git push origin ${{ env.RELEASE_BRANCH_NAME }}
      - run: gem install --no-document git-pr-release
      - name: Create PR for release
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '--squashed' # If you are using squash merge
